version: '3'

services:
  db:
   image: postgres
   container_name: fibonacci-db
   restart: always
   env_file:
   - .env
   ports:
   - 5432:5432
   volumes:
   - /home/db/binance-fibonaccibot:/var/lib/postgresql/data:rw
   - ./container-db/initdb.d:/docker-entrypoint-initdb.d
  telegram:
   build: ./container-telegram
   container_name: fibonacci-telegram
   restart: always
   env_file:
   - .env
   depends_on:
   - cache
  cache:
   image: redis
   command: redis-server --requirepass password
   container_name: fibonacci-redis
   restart: always
   environment:
   - REDIS_REPLICATION_MODE=master
   depends_on:
   - db
   ports:
   - 6379:6379
  crawler:
   build: ./container-crawler
   container_name: fibonacci-crawler
   restart: unless-stopped
   env_file:
   - .env
   depends_on:
   - db
  predictor:
   build: ./container-predictor
   container_name: fibonacci-predictor
   restart: unless-stopped
   env_file:
   - .env
   depends_on:
   - db
   - cache
  webui:
   build: ./container-webui
   container_name: fibonacci-webui
   restart: unless-stopped
   env_file:
   - .env
   depends_on:
   - cache
   ports:
   - "13000:13000"
  analyzer:
   build: ./container-analyzer
   container_name: fibonacci-analyzer
   restart: unless-stopped
   env_file:
   - .env
   depends_on:
   - db
   - cache
