version: '3'

services:
  db:
   image: timescale/timescaledb:latest-pg12
   container_name: fibonacci-timescaledb
   network_mode: "host"
   volumes: 
   - fibonacci-timescaledb:/var/lib/postgresql
   restart: always
   env_file:
   - .env
   ports:
   - 5432:5432
  crawler:
   build: ./container-crawler
   container_name: fibonacci-crawler
   restart: unless-stopped
   env_file:
   - .env
  validator:
   build: ./container-validator
   container_name: fibonacci-validator
   restart: unless-stopped
   env_file:
   - .env
  webui:
   build: ./container-webui
   container_name: fibonacci-webui
   restart: unless-stopped
   network_mode: "host"
   env_file:
   - .env
   ports:
   - "13000:13000"

volumes: 
  fibonacci-timescaledb:
