version: '3'

services:
  db:
   image: timescale/timescaledb:latest-pg12
   container_name: fibonacci-timescaledb
   volumes: 
   - fibonacci-timescaledb:/var/lib/postgresql
   restart: always
   environment:
   - POSTGRES_PASSWORD=password
   ports:
   - 5432:5432
  cache:
   image: redis:latest
   command: redis-server --requirepass password
   container_name: fibonacci-redis
   restart: always
   environment:
   - REDIS_REPLICATION_MODE=master
   ports:
   - 6379:6379
   volumes:
   - $PWD/container-redis/src/redis.conf:/usr/local/etc/redis/redis.conf
  crawler:
   build: ./container-crawler
   container_name: fibonacci-crawler
   restart: unless-stopped
   env_file:
   - .env
   depends_on:
   - db
  validator:
   build: ./container-validator
   container_name: fibonacci-validator
   restart: unless-stopped
   env_file:
   - .env
   depends_on:
   - db
   - crawler
  webui:
   build: ./container-webui
   container_name: fibonacci-webui
   restart: unless-stopped
   env_file:
   - .env
   depends_on:
   - db
   - cache
   ports:
   - "13000:13000"

volumes: 
  fibonacci-timescaledb:
