version: '3'

services:
  db:
   image: timescale/timescaledb:latest-pg12
   container_name: fibonacci-timescaledb
   network_mode: "host"
   volumes: 
   - fibonacci-timescaledb:/var/lib/postgresql
   restart: always
   env_file:
   - .env
   ports:
   - 5432:5432
  crawler:
   build: ./container-crawler
   container_name: fibonacci-crawler
   restart: unless-stopped
   env_file:
   - .env
   depends_on:
   - db
  validator:
   build: ./container-validator
   container_name: fibonacci-validator
   restart: unless-stopped
   env_file:
   - .env
   depends_on:
   - db
  webui:
   build: ./container-webui
   container_name: fibonacci-webui
   restart: unless-stopped
   env_file:
   - .env
   ports:
   - "8080:80"
   environment:
   - NGINX_HOST=binance-fibonaccibot.de
   - NGINX_PORT=80


volumes: 
  fibonacci-timescaledb:
